### ISSUE TITLE
Error parsing WHOIS server when godaddy throws bad domain info

### ISSUE THREAD

**Issue by lapubell** [likexian/whois#17]
This package is great. I've been finding lots of bad info inside WHOIS info from using this, and godaddy is not returning a valid host for a few domains:

```
$ whois the4ccoalition.org
...
Registrar WHOIS Server: whois.godaddy
...

$ whois pgsf.org
...
Registrar WHOIS Server: whois.godaddy
...
```

**Comment by likexian** [comment]
Hello @lapubell 
Thanks for your PR, this is the mistake of Godaddy, they return a wrong `whois server`, I have try to contact them to fix it, but no response. I will merge your PR, but this is not a elegant fix.

---
*If you think this repository is helpful, please share it with friends, thanks.*
