### ISSUE TITLE
Error while Installing Package

### ISSUE THREAD

**Issue by abhisheksingh1234** [likexian/whois#20]
When I do go get I get the following error 

go get -u github.com/likexian/whois
 github.com/likexian/whois
../github.com/likexian/whois/whois.go:100:21: time.Since(start).Milliseconds undefined (type time.Duration has no field or method Milliseconds)

go version go1.10.4 linux/amd64

**Comment by likexian** [comment]
Hello @abhisheksingh1234 
Thanks for your feedback, this is because `go1.10.x` is not support `time.Milliseconds`, please upgrade golang to `1.13.x` and retry.
Or you can use the binary directly, refer to: https://github.com/likexian/whois/tree/master/cmd/whois

**Comment by abhisheksingh1234** [comment]
Thank you upgrading package works.
