### ISSUE TITLE
Error WhoisServer： whois.hichina.com/

### ISSUE THREAD

**Issue by KaranaLJX** [likexian/whois#22]
when dial to  whois.hichina.com/，return error

**Comment by r6c** [comment]
try https://github.com/r6c/whois

**Comment by likexian** [comment]
Hello @KaranaLJX 
Which domain returns this error?

**Comment by KaranaLJX** [comment]
> Hello @KaranaLJX Which domain returns this error?

Hello ，`guanzhanhuajiao.top` and `win2mac.top`

**Comment by likexian** [comment]
Hello @KaranaLJX 
This has been fixed, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*

**Comment by KaranaLJX** [comment]
Thanks a lot，@likexian,i have tried the lastest version,the probelm has been solved.
although I found that requests to this server `whois.hichina.com` always time out 😜

**Comment by likexian** [comment]
> Thanks a lot，@likexian,i have tried the lastest version,the probelm has been solved. although I found that requests to this server `whois.hichina.com` always time out 😜

The timeout should be solved by aliyun.
