### ISSUE TITLE
handle ReferralServer

### ISSUE THREAD

**Issue by quite** [likexian/whois#23]
whois for 144.200.46.16 contains a `ReferralServer`, a token which should be handled. A naive fix follows below. But, the result of it is that whois data from both the referring and the referred server is output. I'm not sure that it should? Perhaps only the latter should be output?

```
diff --git a/whois.go b/whois.go
index efd763f..762ca79 100644
--- a/whois.go
+++ b/whois.go
@@ -217,6 +217,7 @@ func getServer(data string) string {
 	tokens := []string{
 		"Registrar WHOIS Server: ",
 		"whois: ",
+		"ReferralServer: ",
 	}
 
 	for _, token := range tokens {
@@ -226,6 +227,7 @@ func getServer(data string) string {
 			end := strings.Index(data[start:], "\n")
 			server := strings.TrimSpace(data[start : start+end])
 			server = strings.Trim(server, "/")
+			server = strings.TrimPrefix(server, "whois://")
 			return server
 		}
 	}
```

**Comment by quite** [comment]
Just saw whois 172.109.217.241 which has `ReferralServer: rwhois://rwhois.frontiernet.net:4321`. Potential rabbit hole here ;)

**Comment by likexian** [comment]
Hello @quite 
Thanks for your feedback, let me see see.

**Comment by likexian** [comment]
Hello @quite 
This has been fixed, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
