### ISSUE TITLE
Error using custom whois server

### ISSUE THREAD

**Issue by vladtreny** [likexian/whois#29]
If we use a custom whois server, like, whois.biz

`txt, err := c.Whois("excellentlife.biz", "whois.biz")`

here will get a double query 

https://github.com/likexian/whois/blob/da2a39f728fcd78812b314020428cb95e5b75d21/whois.go#L137

The first query will go to whois.biz and return valid data, but then instead of returning this valid response, it will query the default server and return error (biz server used in this library is unstable). 

Should be something like that on #L137

	result, err = c.rawQuery(domain, server, port)
	if err != nil {
		return "", err
	} else {
		return 
	}

**Comment by likexian** [comment]
Hello @vladtreny
I can't reproduce this.
If the whois server return by `whois.biz` is the same as `whois.biz`, it will not doing a double query.
