### ISSUE TITLE
Consider making query stats optional and prefixed by %

### ISSUE THREAD

**Issue by rissson** [likexian/whois#33]
Hi,

I see that all queries are suffixed by some stats about how long that query took: https://github.com/likexian/whois/blob/master/whois.go#L98. Would you consider using `%` as a suffix (as is done by all whois servers I know anyway), and making it optional?

**Comment by likexian** [comment]
Hello @rissson 
Thanks for your feedback.

1. The comment prefix is change to % now.
2. You can use `SetDisableStats(true)` to disable the stats.

---
*If you think this repository is helpful, please share it with friends, thanks.*
