### ISSUE TITLE
whois for IP 34.202.253.227 fails

### ISSUE THREAD

**Issue by Skeeve** [likexian/whois#35]
When querying for whois of IP 34.202.253.227 I get the following result

```
#
# ARIN WHOIS data and services are subject to the Terms of Use
# available at: https://www.arin.net/resources/registry/whois/tou/
#
# If you see inaccuracies in the results, please report at
# https://www.arin.net/resources/registry/whois/inaccuracy_reporting/
#
# Copyright 1997-2023, American Registry for Internet Numbers, Ltd.
#

% Query time: 992 msec
% WHEN: Fri May 26 11:07:35 CEST 2023
```

When [querying online](https://who.is/whois-ip/ip-address/34.202.253.227), I get a result

**Comment by likexian** [comment]
Hello @Skeeve 
It works for me, please change your ip/server and try again.

**Comment by Skeeve** [comment]
What do you mean by that? Isn't the package supposed to use the correct whois-server on its own?

**Comment by likexian** [comment]
The package works fine. It is that your IP is limited by the whois server.

**Comment by likexian** [comment]
Thanks. You are very welcome to implementing the ip parsing.

**Comment by Skeeve** [comment]
If only I knew where to get each information from ;)

**Comment by likexian** [comment]
You are professional !

**Comment by Skeeve** [comment]
Not really. I fiddle around. Sometimes I succeed.

**Comment by likexian** [comment]
^_^
