### ISSUE TITLE
Request: Create new tag

### ISSUE THREAD

**Issue by atc0005** [likexian/whois#36]
The ability to disable referral lookups isn't yet available from a stable tag.

Workaround:

1. `cd /path/to/project`
2. `go get github.com/likexian/whois@f92c1874d6172bd181cf08c35a5c365f1e5dad97`

refs: https://github.com/likexian/whois/compare/v1.15.0...master

Many thanks for this project!

**Comment by likexian** [comment]
Hello @atc0005 
Sorry for the delay, please try again.

---
*If you think this repository is helpful, please share it with friends, thanks.*
