### ISSUE TITLE
Version() returns 1.15.0 instead of 1.15.1

### ISSUE THREAD

**Issue by ugexe** [likexian/whois#40]
https://github.com/likexian/whois/releases/tag/v1.15.1
https://github.com/likexian/whois/blob/62a37fcfd347ac85b4fd9501356119930203fadf/whois.go#L56-L59

**Comment by likexian** [comment]
Hello @ugexe 
Sorry for the issue, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
