### ISSUE TITLE
1.15.3 stopped working on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [likexian/whois#41]
Dear @likexian, @golang developers betrayed Windows 7 users and no longer allow compiling binaries for this OS via the new version of Go. Please, consider using the previous version.

**Comment by likexian** [comment]
Hello @sergeevabc 
Please build it youself in Windows 7.

**Comment by sergeevabc** [comment]
@likexian, what do you mean “build it yourself”? I am a user, who is trained in another field, not a developer. This is your world, where I can only send signals.
