### ISSUE TITLE
%referral and rwhois urls are not handled by getServer()

### ISSUE THREAD

**Issue by gavincarr** [likexian/whois#49]
The whois server at `rwhois.shawcable.net:4321` returns a referral response for ip `174.0.0.1` that looks like this:

```
%rwhois V-1.5:003fff:00 rs1so.cg.shawcable.net (by Network Solutions, Inc. V-1.5.9.5)
%referral rwhois://root.rwhois.net:4321/auth-area=.
%ok
```

There are a couple of issues here:

1. The `%referral` syntax isn't handled by `getServer()`

2. The server/port extraction code in `getServer()` assumes everything after the scheme is a `server[:port]`, so we end up with port having the non-numeric url path attached.

PR fixing these issues to follow. Thanks!

**Comment by likexian** [comment]
Hello @gavincarr 
Thanks for your works.

---
*If you think this repository is helpful, please share it with friends, thanks.*
